# Generated by Django 4.0.6 on 2022-08-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('email', models.EmailField(max_length=35, verbose_name='email')),
                ('send_type', models.CharField(choices=[('register', 'register'), ('forget', 'forget password')], default='register', max_length=20)),
            ],
            options={
                'verbose_name': 'verification code',
                'verbose_name_plural': 'verification code',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User data', 'verbose_name_plural': 'User data'},
        ),
    ]
